FROM maven:3.8-jdk-11-slim AS dep-cache
WORKDIR /opt
COPY ./pom.xml /opt/pom.xml
COPY ./connector/pom.xml /opt/connector/pom.xml
COPY ./integration-tests/pom.xml /opt/integration-tests/pom.xml
COPY ./integration-tests/cp-server/pom.xml /opt/integration-tests/cp-server/pom.xml
COPY ./integration-tests/commons/pom.xml /opt/integration-tests/commons/pom.xml
COPY ./integration-tests/debezium/pom.xml /opt/integration-tests/debezium/pom.xml
COPY ./kafka-questdb-connector-samples/pom.xml /opt/kafka-questdb-connector-samples/pom.xml
RUN mvn -B -f ./pom.xml -pl connector dependency:go-offline

FROM dep-cache AS builder
WORKDIR /opt
COPY ./connector/src /opt/connector/src
RUN mvn install -pl connector -Dmaven.test.skip
RUN cd /opt/connector/target && tar xzvf ./kafka-questdb-connector-*-bin.tar.gz

FROM confluentinc/cp-kafka-connect:7.2.1
COPY --from=builder /opt/connector/target/kafka-questdb-connector/* /usr/share/java/kafka/