apiVersion: 1
datasources:
  - name: QuestDB
    type: postgres
    url: questdb:8812
    user: admin
    secureJsonData:
      password: "quest"
    jsonData:
      database: qdb
      sslmode: "disable"
      timescaledb: false
